# Generated by Django 5.1.1 on 2024-10-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_car_num_tel_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='num_tel',
        ),
    ]
