# Generated by Django 5.1.1 on 2024-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_remove_car_num_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='num_tel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
