# Generated by Django 5.1.1 on 2024-10-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_remove_car_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
