# Generated by Django 5.1.1 on 2024-10-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0010_alter_testdrive_date_alter_testdrive_userdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
